# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Terrafile < Formula
  desc "Systematically manage external modules from Github for use in Terraform."
  homepage "https://github.com/coretech/terrafile"
  version "0.7"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/coretech/terrafile/releases/download/v0.7/terrafile_0.7_Darwin_arm64.tar.gz"
      sha256 "b1c0fdcc2215b786cf4f77beaf7e9a5b93f6aff6d75b34e0ede234b5581cfd59"

      def install
        bin.install "terrafile"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/coretech/terrafile/releases/download/v0.7/terrafile_0.7_Darwin_x86_64.tar.gz"
      sha256 "370faa1e2ccce22f4ab9f1ff1a6790a43cedb3291943208a58e3092593cbaf8e"

      def install
        bin.install "terrafile"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/coretech/terrafile/releases/download/v0.7/terrafile_0.7_Linux_arm64.tar.gz"
      sha256 "eb293b5735760e29002831348265d0c91a63ce019eb40b2039a9d8ab538af1ac"

      def install
        bin.install "terrafile"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/coretech/terrafile/releases/download/v0.7/terrafile_0.7_Linux_x86_64.tar.gz"
      sha256 "85be37110649408fa9fcc58669e4944c7a0fae1a40c070bc50cbe20efac52e16"

      def install
        bin.install "terrafile"
      end
    end
  end
end
