# This file was generated by GoReleaser. DO NOT EDIT.
class Terrafile < Formula
  desc "Systematically manage external modules from Github for use in Terraform."
  homepage "https://github.com/coretech/terrafile"
  version "0.6"

  if OS.mac?
    url "https://github.com/coretech/terrafile/releases/download/v0.6/terrafile_0.6_Darwin_x86_64.tar.gz"
    sha256 "290cd755821a3cc9dc8901abfb5c3bcb9aedc344f7de6bf9512064de96308f06"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/coretech/terrafile/releases/download/v0.6/terrafile_0.6_Linux_x86_64.tar.gz"
      sha256 "770993ee36c77a464f31ab0980cd852199013c3486dde92fa34e8e7ee6a77555"
    end
  end

  def install
    bin.install "terrafile"
  end
end
